- shell_loop.c
> moved initialization of one var into the loop

- bashlist
- main.c
- main.h
- shell_loop.c
- shellf_destruct.c
- added argc, argv to main
- passed argv to multiple locations
- argv[0] needed for one error message
- adjusted prototypes
> Added Filename Operability

- shell_loop.c
- added a variable to track the error number
- exiting execve fail with error number
> Correct Exit Status

- shell_loop.c
changed exit to return in case of execve failure
> exit to return request

- main.h
- shell_loop.c
- shellf_destruct.c
- added an existance check on cmd
- moved fprintf error to shellLoop
- adjusted runCommand signature
- prepared a section for the incoming function customCmd
> added a check before fork is called

- shell_loop.c
- supersimp.c
- added most of the tasks from super simple shell to a file for reference
- probably useful in addressing all the env questions coming up
> Added SuperSimpleShell for Env Reference

- shell_loop.c
- fixed strtok issues
- fixed memory leaks
- fixed tokens
- multiple args in interactive should work now.
> Back to Functioning

- env.c
- freed a passed variable to buildListPath
- valgrind shows no leaks with three different tests
> Memory Safe Again

- shell_loop.c
- adjust isatty() to handle interactive mode correctly
- included logic to handle styling output
> changed is isatty implementation

- bashlist
- shell_loop.c
- added an isatty to the command check section to check if it leads in the right direction
> testing isatty exit vs return

- shell_loop.c
- Utilized WIFEXITED & WEXITSTATUS to extract exit status of child process
- Utilized errno in doing so
- Didn't hardcode values
- Values are system-specific and might not align with expected code
- will have to hardcode if it doesn't match
> Exit Status Update

- main.h
- shell_loop.c
- updated function headers
- added easter egg comment
> Updated function headers

- env2.c
- shell_loop.c
- added function comments and adjusted executeIfValid with hardcode error message for 127
- unsure why strerror(127) shows "Key has expired"
> Hardcoded error message for 127

- shell_loop.c
- removed commented debug commands
- tested out multiline echo of "ls" variations and it checked out.
- perhaps it'll work magically this time?
> removed commented debug commands

- shell_loop.c
> added delimiters for strtok

- shell_loop.c
> added delims in other area

- shell_loop.c
> hardcoded error 13

- custom_commands.c
- env.c
- shell_loop.c
- commented out a line to see if it was causing issues with new delimiters
> removed newline remover line

- custom_commands.c
#July 29th 10:27 am
changed commenting
> C90 change

- custom_commands.c
- env2.c
- main.h
> added setenv and unsetenv funcitonality. needs debugging
